'use server';

import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Download } from 'lucide-react';
import { requireInternalUser } from '@/lib/auth/server';
import { getReportById } from '@/lib/services/reports';
import { PageHeader } from '@/components/shared/PageHeader';
import { StatusBadge } from '@/components/shared/StatusBadge';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

interface ReportDetailPageProps {
  params: Promise<{ id: string }>;
}

const REPORT_TYPE_MAP: Record<string, string> = {
  final_screening: 'Final Screening',
  interim: 'Interim Report',
  compliance_summary: 'Compliance Summary',
};

/**
 * Format file size to human-readable format (KB, MB)
 */
function formatFileSize(bytes: number | null): string {
  if (!bytes) return '-';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/**
 * Format date to UK format: "4 Apr 2026 at 14:30"
 */
function formatDateTime(dateStr: string | null): string {
  if (!dateStr) return '-';
  const date = new Date(dateStr);
  return date.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

export async function generateMetadata({ params }: ReportDetailPageProps) {
  const { id } = await params;
  const report = await getReportById(id);
  return {
    title: `Report ${report?.case_reference || id} — Instant Check`,
  };
}

export default async function ReportDetailPage({ params }: ReportDetailPageProps) {
  await requireInternalUser();

  const { id } = await params;
  const report = await getReportById(id);

  if (!report) {
    notFound();
  }

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <PageHeader
        title={`${REPORT_TYPE_MAP[report.report_type] || report.report_type} — ${report.case_reference}`}
        backHref="/reports"
      />

      {/* Main Grid */}
      <div className="grid gap-6">
        {/* Report Info Card */}
        <Card>
          <CardHeader>
            <CardTitle>Report Information</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
              <div>
                <p className="text-xs font-medium text-gray-600 uppercase">
                  Report Type
                </p>
                <p className="mt-1 text-sm font-semibold text-gray-900">
                  {REPORT_TYPE_MAP[report.report_type] || report.report_type}
                </p>
              </div>

              <div>
                <p className="text-xs font-medium text-gray-600 uppercase">
                  Status
                </p>
                <div className="mt-1">
                  <StatusBadge status={report.status} />
                </div>
              </div>

              <div>
                <p className="text-xs font-medium text-gray-600 uppercase">
                  Version
                </p>
                <p className="mt-1 text-sm font-semibold text-gray-900">
                  v{report.version}
                </p>
              </div>

              <div>
                <p className="text-xs font-medium text-gray-600 uppercase">
                  File Size
                </p>
                <p className="mt-1 text-sm font-semibold text-gray-900">
                  {formatFileSize(report.file_size)}
                </p>
              </div>
            </div>

            <div className="border-t border-gray-200 pt-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-xs font-medium text-gray-600 uppercase">
                    Generated By
                  </p>
                  <p className="mt-1 text-sm text-gray-900">
                    {report.generated_by || '-'}
                  </p>
                </div>

                <div>
                  <p className="text-xs font-medium text-gray-600 uppercase">
                    Generated At
                  </p>
                  <p className="mt-1 text-sm text-gray-900">
                    {formatDateTime(report.generated_at)}
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Case Info Card */}
        <Card>
          <CardHeader>
            <CardTitle>Case Information</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-xs font-medium text-gray-600 uppercase">
                  Case Reference
                </p>
                <Link
                  href={`/cases/${report.case_id}`}
                  className="mt-1 text-sm font-semibold text-blue-600 hover:text-blue-900"
                >
                  {report.case_reference}
                </Link>
              </div>

              <div>
                <p className="text-xs font-medium text-gray-600 uppercase">
                  Candidate Name
                </p>
                <p className="mt-1 text-sm font-semibold text-gray-900">
                  {report.candidate_name}
                </p>
              </div>
            </div>

            <div className="border-t border-gray-200 pt-4">
              <p className="text-xs font-medium text-gray-600 uppercase">
                Organisation ID
              </p>
              <p className="mt-1 text-sm font-mono text-gray-600">
                {report.organisation_id}
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Download Section */}
        {report.status === 'ready' && (
          <Card>
            <CardHeader>
              <CardTitle>Download Report</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="mb-4 text-sm text-gray-600">
                The report is ready to download.
              </p>
              <Link href={`/api/reports/${report.id}/download`}>
                <Button>
                  <Download className="mr-2 h-4 w-4" />
                  Download PDF
                </Button>
              </Link>
            </CardContent>
          </Card>
        )}

        {/* Metadata Section */}
        {Object.keys(report.metadata).length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle>Metadata</CardTitle>
            </CardHeader>
            <CardContent>
              <pre className="overflow-x-auto rounded-lg bg-gray-50 p-4 text-xs font-mono text-gray-600">
                {JSON.stringify(report.metadata, null, 2)}
              </pre>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
